export const settings = {
    taxes: {
        headers: [
            "Tên công ty",
            "Mã số thuế",
            "Địa chỉ",
            "Đại diện",
            "Số điện thoại",
            "Email",
            "Participants",
        ],
        fields: [
            "name",
            "taxCode",
            "address",
            "representative",
            "phone",
            "email",
            "participants",
        ],
        colsWidth: [20, 20, 20, 20, 20, 20, 20],
    },
    users: {
        headers: [
            "Tên người dùng",
            "Email",
            "Mật khẩu",
            "Số điện thoại",
            "Vai trò",
        ],
        fields: ["name", "email", "password", "phone", "role"],
        colsWidth: [20, 20, 20, 20, 20],
    },
    products: {
        headers: [
            "Tên sản phẩm",
            "Loại",
            "Số lượng",
            "Giá bán lẻ",
            "Nhà cung cấp",
        ],
        fields: ["name", "category", "quantity", "price", "suppliers"],
        colsWidth: [20, 20, 20, 20, 20],
    },
    customers: {
        headers: [
            "Tên khách hàng",
            "Địa chỉ",
            "Số điện thoại",
            "Người đặt hàng",
            "Email",
            "Người phụ trách",
            "Ghi chú",
        ],
        fields: [
            "name",
            "address",
            "phone",
            "placer",
            "email",
            "curator",
            "note",
        ],
        colsWidth: [20, 20, 20, 20, 20, 20, 20],
    },
    shippings: {
        headers: ["Tên đơn vị", "Địa chỉ", "Số điện thoại", "Ghi chú"],
        fields: ["name", "address", "phone", "note"],
        colsWidth: [175, 400, 75, 200],
    },
    suppliers: {
        headers: [
            "Tên đơn vị",
            "Địa chỉ",
            "Người phụ trách",
            "Số điện thoại",
            "Ghi chú",
        ],
        fields: ["name", "address", "contact", "phone", "note"],
        colsWidth: [20, 20, 20, 20, 20],
    },
};
